### ISSUE TITLE
No such file or directory when CSS file is not in /css

### ISSUE THREAD

**Issue by huphtur** [mhanberg/jekyll-purgecss#1]
Playing around with the [jekyll-tailwind-starter](https://github.com/mhanberg/jekyll-tailwind-starter) project, I renamed the `/css` dir to `/assets` and adjusted [line 3](https://github.com/mhanberg/jekyll-tailwind-starter/blob/master/purgecss.config.js#L3) of  `purgecss.config.js` to: `css: ["./_site/assets/site.css"],`

When running `JEKYLL_ENV=production bundle exec jekyll build` I get following error: `ENOENT: no such file or directory, open '_site/css//site.css'`

Any idea how to resolve this?

**Comment by mhanberg** [comment]
Not off the top of my head. 

I can play around with this evening.

Thanks for reporting this!

**Comment by mhanberg** [comment]
@huphtur fixed and released: https://github.com/mhanberg/jekyll-purgecss/commit/5b706fa31c247bc6aee78b526a79ef4be536b588

Upgrade to v0.1.1 and add the following to your `_config.yml`

```yml
css_dir: "assets"
```

and it should work.
