### ISSUE TITLE
CSS not purged?

### ISSUE THREAD

**Issue by DirtyF** [mhanberg/jekyll-purgecss#2]
👋 

I just tested the plugin with `css_dir: assets/css` and the CSS file has the exact same output as without the plugin.

Running `jekyll build --verbose`, don't display any info on post:write treatment

When I run `./node_modules/purgecss/bin/purgecss --config ./purgecss.config.js --out _site/assets/css` it gets purged.

**Comment by mhanberg** [comment]
jekyll-purgecss will only run in production. 

To run this on your local machine, you will need to run `JEKYLL_ENV=production [bundle exec] jekyll build`

LMK if that solves your issue!

**Comment by DirtyF** [comment]
Live in production on Netlify :shipit: 

Here's my `.netlify.toml` in case you want to add a section in the docs:

```
[build]
  publish = "_site"
  command = "npm i -D purgecss && bundle exec jekyll build --config _config.yml,_config_prod.yml"

[context.production.environment]
  JEKYLL_ENV = "production"
```
