### ISSUE TITLE
Jekyll PurgeCSS works with Github Pages?

### ISSUE THREAD

**Issue by coderdiaz** [mhanberg/jekyll-purgecss#3]
The `jekyll-purgecss` uses the `purgecss` module from `npm packages` but Github Pages is only for try static pages, therefore, the node modules do not exist.

This works in Github Pages or only on Ruby servers with `node` installed?

**Comment by mhanberg** [comment]
This requires a production environment with Node.js.

Sadly Github Pages does not have support for this.

I would suggest switching to [Netlify](https://www.netlify.com), I use it for my [personal site](github.com/mhanberg/blog) along with `jekyll-purgecss`.

You can also look at https://github.com/mhanberg/jekyll-tailwind-starter#deployment for an example of how to use jekyll-purgecss with Netlify.

**Comment by coderdiaz** [comment]
@mhanberg Ok, thanks man! 👍

**Comment by gamue** [comment]
Wanted to share that I use the plugin with GitHub pages, however you need to take care of the build process on your own. Using GitHub Actions that isn't a big deal though.

Feel free to check out https://github.com/gamue/gamue.github.io/blob/master/.github/workflows/deploy-page.yml for the source-code

**Comment by mhanberg** [comment]
I would welcome a PR that documents this process 😄
