### ISSUE TITLE
error: unknown option '--out' with purgecss 2.0.5

### ISSUE THREAD

**Issue by huphtur** [mhanberg/jekyll-purgecss#7]
Upgrading purgecss from v1 to v2, gives: `error: unknown option '--out'` when running `JEKYLL_ENV=production bundle exec jekyll build`. 

Tried this on [jekyll-tailwind-starter](https://github.com/mhanberg/jekyll-tailwind-starter) and on [jekyll-tailwind-starter-plus](https://github.com/huphtur/jekyll-tailwind-starter-plus/), same error :(

**Comment by huphtur** [comment]
perhaps related: https://github.com/FullHuman/purgecss/issues/262

**Comment by noblesilence** [comment]
I got the same error when I changed from *.html to index.html.
`purgecss --css css/bootstrap.min.css --content index.html --out build/css`

**Comment by jskn** [comment]
Hi, I have the same issue. Anyone found a solution/workaround?

**Comment by mhanberg** [comment]
Closed by 5daec5c51342229a6af645bb6872623dc55d0cb1

**Comment by jskn** [comment]
Great, thanks! But still have some issues. Get "throw _iteratorError" and CssSyntaxError "Uknown word" and when building it output all HTML.

But will give this some more time.
